project3/main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
path('marctemplatelist/', views.MarcTemplateList.as_view(), name='marctemplatelist'),
path('marctemplate/add/', views.MarcTemplateAddView.as_view(), name='marctemplate-add'),
path('marctemplate/update/<int:pk>/', views.MarcTemplateUpdateView.as_view(), name='marctemplate-edit'),
path('marctemplate/delete/<int:pk>/', views.MarcTemplateDeleteView.as_view(), name='marctemplate-delete'),

]

project3/project3/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic.base import RedirectView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('', RedirectView.as_view(url='main/marctemplatelist/')),
]

project3/main/models.py
from django.db import models
from django.urls import reverse

class MarcTemplate(models.Model):
    MarcTemplateTitle= models.CharField(max_length=200)
    biblio_type_id= models.CharField(max_length=200)
    Description = models.CharField(max_length=200)
    jsonObject = models.TextField()
 
    #def get_absolute_url(self):
    #    return reverse('main:marctemplatelist')

project3/main/views.py
from django.shortcuts import render
from .models import MarcTemplate
from django.views import generic

class MarcTemplateList(generic.ListView):
    template_name='main/marctemplate_list.html'
    context_object_name='All_MarcTemplate'

    def get_queryset(self):
        return MarcTemplate.objects.all()

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView,UpdateView,DeleteView
class MarcTemplateAddView(CreateView):
    model=MarcTemplate
    template_name = 'main/marctemplate_form.html'
    success_url=reverse_lazy('main:marctemplatelist')
    fields=['MarcTemplateTitle','biblio_type_id','Description','jsonObject']

class MarcTemplateUpdateView(UpdateView):
    model=MarcTemplate
    template_name = 'main/marctemplate_form.html'
    success_url=reverse_lazy('main:marctemplatelist')

    fields=['MarcTemplateTitle','biblio_type_id','Description','jsonObject']

class MarcTemplateDeleteView(DeleteView):
    model=MarcTemplate
    success_url=reverse_lazy('main:marctemplatelist')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


        

project3/main/templates/home.html
 {% load static %} 
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>


    {% block content %}
        Body content
    {% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

project3/main/templates/main/marctemplate_form.html
{% extends "home.html" %}

{% block content %}
<form class="form-horizontal" method="POST" action="" enctype="multipart/form-data">
    {% csrf_token%}
    <table>
        {%for field in form  %}
          <tr>
              <td>{{field.label_tag}}</td> 
              <td>{{field}}</td>
              <td>{{field.errors}}</td>
          </tr>
        {%endfor%}
    </table>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
  </form>
{% endblock %}


project3/main/templates/main/marctemplate_list.html
{% extends "home.html" %}

{% block content %}
    <a class="btn btn-primary" href='{%url 'main:marctemplate-add' %}'> + Add New Template</a>

    {% if All_MarcTemplate %}
        <table border="1" width=100%>
            {% for MarcTemplate in All_MarcTemplate %}
              <tr>
                  <td>{{MarcTemplate.MarcTemplateTitle}}</td>
                  <td>{{MarcTemplate.Description}} </td>
                  <td>{{MarcTemplate.jsonObject}}</td>
                  <td>
                      <a href="{% url 'main:marctemplate-edit' MarcTemplate.pk  %}"> >Edit</a>
                      <a href="{% url 'main:marctemplate-delete' MarcTemplate.pk %}"> Delete</a>
                  </td>
              </tr>
            {% endfor %}
        </table>
    {% endif %}

{% endblock %}